name: EPD PDF Scraper 2025

on:
  schedule:
    - cron: '0 */3 * * *'   # every 3 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade aiohttp playwright pypdf psutil aiosmtplib
          python -m playwright install chromium

      - name: Run scraper
        shell: powershell
        run: python scraper.py

      - name: Commit new PDFs
        shell: powershell
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloaded_pdfs/pdfs/* || exit 0
          git commit -m "Auto: Add new EPD PDFs $(Get-Date -Format 'yyyy-MM-dd HH:mm')" || echo "No new PDFs"
          git push origin main || echo "Nothing to push"
