name: EPD PDF Scraper 2025

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Python
        shell: powershell
        run: |
          python --version
          Write-Host "Python executable: $(python -c 'import sys; print(sys.executable)')"

      - name: Install dependencies (no-fail)
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          try { pip install -r requirements.txt } catch { Write-Host "pip install -r requirements.txt failed, continuing" }
          try { python -m playwright install chromium } catch { Write-Host "playwright install failed (already installed?), continuing" }

      - name: Run scraper
        shell: powershell
        run: |
          python scraper.py

      - name: Commit new PDFs
        shell: powershell
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if (Test-Path downloaded_pdfs/pdfs) {
            git add downloaded_pdfs/pdfs/* 2>$null
            try {
              git commit -m "Auto: Add new EPD PDFs $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -a 2>$null
            } catch {
              Write-Host "No new PDFs"
            }
            git push origin main
          } else {
            Write-Host "No download folder present"
          }
