name: EPD PDF Scraper 2025

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Python
        shell: pwsh
        run: |
          python --version
          Write-Host "Python executable: $(python -c 'import sys; print(sys.executable)')"

      - name: Install dependencies (no-fail)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          # install requirements; if fails the job continues
          try {
            pip install -r requirements.txt
          } catch {
            Write-Host "pip install -r requirements.txt failed, continuing"
          }
          # install playwright browsers via python -m to guarantee correct interpreter
          try {
            python -m playwright install chromium
          } catch {
            Write-Host "playwright install failed (already installed?), continuing"
          }

      - name: Run scraper
        shell: pwsh
        run: |
          python scraper.py

      - name: Commit new PDFs
        shell: pwsh
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if (Test-Path downloaded_pdfs/pdfs) {
            git add downloaded_pdfs/pdfs/* 2>$null
            git commit -m "Auto: Add new EPD PDFs $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -a 2>$null || Write-Host "No new PDFs"
            git push origin main
          } else {
            Write-Host "No download folder present"
          }
