name: EPD PDF Scraper 2025

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install aiohttp playwright pypdf psutil aiosmtplib
          playwright install --with-deps chromium
      - name: Run scraper
        run: python scraper.py
        env:
          EPD_SCAPER_TOKEN: ${{ secrets.EPD_SCAPER_TOKEN }}
      - name: Check for PDFs and commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          rm -rf .git/refs/ORIG_HEAD .git/refs/remotes/origin/HEAD
          git remote prune origin
          git fetch origin
          git checkout main
          git reset --hard origin/main
          if [ -d "downloaded_pdfs/pdfs" ] && [ "$(ls -A downloaded_pdfs/pdfs)" ]; then
            git add downloaded_pdfs/pdfs/*
            git commit -m "Auto: Add new EPD PDFs $(date)" || echo "No changes to commit"
          else
            echo "No PDFs to commit"
          fi
          git push origin main
        env:
          EPD_SCAPER_TOKEN: ${{ secrets.EPD_SCAPER_TOKEN }}